name: CD

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  start-test-environment:
    runs-on: self-hosted
    if: ${{ github.event.action != 'closed' }}
    steps:
      - run: echo "Start"
      - run: pwd
      - run: ls -al
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.event.pull_request.number }}"
      - run: echo "${{ github.event.pull_request.head.ref }}"
  stop-test-environment:
    runs-on: self-hosted
    if: ${{ github.event.action == 'closed' }}
    steps:
      - run: echo "Stop"
